// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD0aCX7WeJkBkkwHDk8OjXadQFPUC7KdA',
    appId: '1:215801002709:android:cd8fba1de81183f459c05c',
    messagingSenderId: '215801002709',
    projectId: 'calender-scheduler-451aa',
    storageBucket: 'calender-scheduler-451aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfHyZvRKasBvnI-Oz63bnCWm-ujJrBkyc',
    appId: '1:215801002709:ios:9719c2541981033059c05c',
    messagingSenderId: '215801002709',
    projectId: 'calender-scheduler-451aa',
    storageBucket: 'calender-scheduler-451aa.appspot.com',
    androidClientId: '215801002709-5ccsjlvgef40t1mulutqfbjqfdoju4n6.apps.googleusercontent.com',
    iosClientId: '215801002709-rl4jjla5e5ufj3fv9hl7bu2995f84bh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );
}
